# Generated by Django 5.2.6 on 2025-10-25 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año de fabricación')),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kilometraje', models.IntegerField(help_text='Kilometraje en kilómetros')),
                ('estado', models.CharField(help_text='Estado del auto: Nuevo, Usado', max_length=10)),
                ('imagen_auto', models.ImageField(blank=True, null=True, upload_to='autos/', verbose_name='Imagen del auto')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
                'ordering': ['-anio', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text='Tipo de vendedor: Agencia, Privado, Concesionario', max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('puntuacion', models.IntegerField(help_text='Puntuación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_resena', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='autos.auto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='autos.usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_resena'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='autos.auto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='autos.usuario')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='autos.vendedor', verbose_name='Vendedor'),
        ),
    ]
